#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
workspace_root="$(cd -- "$script_dir/../../.." && pwd)"
python_bin="$workspace_root/FFNN/.venv/bin/python"
symbolic_script="$script_dir/Symbolic_Regression/nn_to_symbolic.py"

# =============================================================================
# Symbolic-regression configuration / 符号回归配置
# Command-line arguments with the same names override these defaults.
# 同名命令行参数会覆盖这里的默认设置。
# =============================================================================

# Data workflow / 数据模式: synthetic | experimental
# synthetic uses files generated by run_train.sh; experimental uses the paths below.
# synthetic 使用 run_train.sh 生成的数据；experimental 使用下方实验数据路径。
workflow_mode="experimental"

# Synthetic model directory name / 合成模型目录名: ogden | mooney_rivlin | arruda_boyce
# Only used when workflow_mode="synthetic".
synthetic_model="ogden"

# PySR feature space / 符号回归变量空间:
#   invariants : fit W(I1, I2)
#   stretches  : fit W(lambda1, lambda2, lambda3)
feature_space="invariants"

# Valanis-Landel decomposition / Valanis–Landel 可分离假设:
# true  -> W = w(lambda1) + w(lambda2) + w(lambda3)
# false -> unrestricted expression in the selected feature space
# This option requires feature_space="stretches".
# 此选项只能与 stretches 一起使用。
use_valanis_landel=false

# Combined loss: energy_loss_weight * energy_MSE + stress_loss_weight * stress_MSE
# 联合损失：能量权重 × 能量 MSE + 应力权重 × 应力 MSE
# stress_loss_weight=0 disables candidate stress differentiation and is faster.
# 应力权重为 0 时跳过候选表达式的应力求导，运行更快。
energy_loss_weight="1.0"
stress_loss_weight="1.0"

# Number of NN samples exported along each loading path / 每条加载路径的 NN 采样点数
ut_points="16"
ps_points="16"
et_points="16"

# PySR search hyperparameters / PySR 搜索超参数
niterations="80"        # Number of evolutionary iterations / 进化迭代次数
population_size="60"    # Individuals per population / 每个种群的个体数
populations="12"        # Number of populations / 种群数量
maxsize="18"            # Maximum expression-tree complexity / 表达式最大复杂度
binary_operators=("+" "-" "*" "/") # Allowed binary operators / 允许的二元算子
deterministic=true       # true uses reproducible serial search / true 使用可复现串行搜索

# Post-fit simplification / 拟合后简化
# Iteratively removes additive terms, refits remaining coefficients, and accepts
# the simpler model when experimental-stress RMSE rises by no more than 2%.
# 逐项删除、重新拟合剩余系数；实验应力 RMSE 增幅不超过 2% 时接受简化模型。
simplify_expression=true
simplify_rmse_tolerance="0.02"
simplify_energy_weight="0.0"
simplify_stress_weight="1.0"

# Synthetic stretch ranges. These must match run_train.sh.
# 合成数据伸长范围，必须与 run_train.sh 保持一致。
synthetic_ut_min="1.0"
synthetic_ut_max="3.0"
synthetic_ps_min="1.0"
synthetic_ps_max="3.0"
synthetic_et_min="1.0"
synthetic_et_max="3.0"

sr_output_dir="$script_dir/output/SR_output"
sr_output_csv="$sr_output_dir/nn_loadcase_samples.csv"

# Experimental datasets. Column 1 is nominal stress and column 2 is stretch.
# 实验数据：第 1 列为名义应力，第 2 列为伸长比。
ut_dataset="$workspace_root/FFNN/fitting-data-PK/Treloar_1944/UT/stress_stretch.txt"
ps_dataset="$workspace_root/FFNN/fitting-data-PK/Treloar_1944/PS/stress_stretch.txt"
et_dataset="$workspace_root/FFNN/fitting-data-PK/Treloar_1944/ET/stress_stretch.txt"

extra_symbolic_args=()

while [[ $# -gt 0 ]]; do
	case "$1" in
		--workflow)
			if [[ $# -lt 2 ]]; then
				echo "Missing value after --workflow" >&2
				exit 1
			fi
			workflow_mode="$2"
			shift 2
			;;
		--synthetic)
			workflow_mode="synthetic"
			shift
			;;
		--experimental)
			workflow_mode="experimental"
			shift
			;;
		--synthetic-model)
			synthetic_model="$2"
			shift 2
			;;
		--ut-dataset)
			ut_dataset="$2"
			shift 2
			;;
		--ps-dataset)
			ps_dataset="$2"
			shift 2
			;;
		--et-dataset)
			et_dataset="$2"
			shift 2
			;;
		--feature-space)
			feature_space="$2"
			shift 2
			;;
		--valanis-landel)
			use_valanis_landel=true
			shift
			;;
		--no-valanis-landel)
			use_valanis_landel=false
			shift
			;;
		--energy-loss-weight)
			energy_loss_weight="$2"
			shift 2
			;;
		--stress-loss-weight)
			stress_loss_weight="$2"
			shift 2
			;;
		--simplify-expression)
			simplify_expression=true
			shift
			;;
		--no-simplify-expression)
			simplify_expression=false
			shift
			;;
		--simplify-rmse-tolerance)
			simplify_rmse_tolerance="$2"
			shift 2
			;;
		--simplify-energy-weight)
			simplify_energy_weight="$2"
			shift 2
			;;
		--simplify-stress-weight)
			simplify_stress_weight="$2"
			shift 2
			;;
		*)
			extra_symbolic_args+=("$1")
			shift
			;;
	esac
done

if [[ "$workflow_mode" != "synthetic" && "$workflow_mode" != "experimental" ]]; then
	echo "Unsupported workflow: $workflow_mode. Expected synthetic or experimental." >&2
	exit 1
fi

if [[ "$feature_space" != "invariants" && "$feature_space" != "stretches" ]]; then
	echo "Unsupported feature space: $feature_space. Expected invariants or stretches." >&2
	exit 1
fi

if [[ "$use_valanis_landel" == true && "$feature_space" != "stretches" ]]; then
	echo "Valanis-Landel regression requires feature_space=stretches." >&2
	exit 1
fi

if [[ ! -x "$python_bin" ]]; then
	echo "Python interpreter not found: $python_bin" >&2
	exit 1
fi

stretch_range_from_dataset() {
	local dataset_path="$1"
	awk 'NR==1{min=$2; max=$2} {if($2<min) min=$2; if($2>max) max=$2} END{printf "%.8f %.8f\n", min, max}' "$dataset_path"
}

if [[ "$workflow_mode" == "experimental" ]]; then
	read -r ut_stretch_min ut_stretch_max < <(stretch_range_from_dataset "$ut_dataset")
	read -r ps_stretch_min ps_stretch_max < <(stretch_range_from_dataset "$ps_dataset")
	read -r et_stretch_min et_stretch_max < <(stretch_range_from_dataset "$et_dataset")
else
	ut_dataset="$script_dir/synthetic_data/$synthetic_model/UT/stress_stretch.txt"
	ps_dataset="$script_dir/synthetic_data/$synthetic_model/PS/stress_stretch.txt"
	et_dataset="$script_dir/synthetic_data/$synthetic_model/ET/stress_stretch.txt"
	ut_stretch_min="$synthetic_ut_min"
	ut_stretch_max="$synthetic_ut_max"
	ps_stretch_min="$synthetic_ps_min"
	ps_stretch_max="$synthetic_ps_max"
	et_stretch_min="$synthetic_et_min"
	et_stretch_max="$synthetic_et_max"
fi

symbolic_args=(
	pipeline
	# Sample the trained NN along UT/PS/ET loading paths.
	# 沿 UT/PS/ET 加载路径对训练后的 NN 采样。
	--sampling-mode loadcases
	--output-csv "$sr_output_csv"
	--output-dir "$sr_output_dir"
	--feature-space "$feature_space"
	--energy-loss-weight "$energy_loss_weight"
	--stress-loss-weight "$stress_loss_weight"
	--ut-points "$ut_points"
	--ps-points "$ps_points"
	--et-points "$et_points"
	--ut-stretch-range "$ut_stretch_min" "$ut_stretch_max"
	--ps-stretch-range "$ps_stretch_min" "$ps_stretch_max"
	--et-stretch-range "$et_stretch_min" "$et_stretch_max"
	--niterations "$niterations"
	--population-size "$population_size"
	--populations "$populations"
	--maxsize "$maxsize"
	--binary-operators "${binary_operators[@]}"
	--simplify-rmse-tolerance "$simplify_rmse_tolerance"
	--simplify-energy-weight "$simplify_energy_weight"
	--simplify-stress-weight "$simplify_stress_weight"
	--ut-dataset "$ut_dataset"
	--ps-dataset "$ps_dataset"
	--et-dataset "$et_dataset"
)

if [[ "$simplify_expression" == true ]]; then
	symbolic_args+=(--simplify-expression)
fi

if [[ "$use_valanis_landel" == true ]]; then
	symbolic_args+=(--valanis-landel)
fi

if [[ "$deterministic" == true ]]; then
	symbolic_args+=(--deterministic)
fi

echo "Running symbolic regression"
echo "Workflow mode: $workflow_mode"
echo "Feature space: $feature_space"
echo "Valanis-Landel: $use_valanis_landel"
echo "Energy loss weight: $energy_loss_weight"
echo "Stress loss weight: $stress_loss_weight"
echo "Post-fit simplification: $simplify_expression"
if [[ "$simplify_expression" == true ]]; then
	echo "Simplification RMSE tolerance: $simplify_rmse_tolerance"
	echo "Simplification energy/stress weights: $simplify_energy_weight / $simplify_stress_weight"
fi
"$python_bin" "$symbolic_script" "${symbolic_args[@]}" "${extra_symbolic_args[@]}"
